In [6]:
import pandas as pd
import numpy as np

In [26]:
#To read the csv file

df = pd.read_csv('OLX_cars_dataset00.csv')
df.head()

,Ad ID,Car Name,Make,Model,Year,KM's driven,Price,Fuel,Registration city,Car documents,Assembly,Transmission,Condition,Seller Location,Description,Car Features,Images URL's,Car Profile
0,1079071571,fresh import Passo 2021model,Toyota,Passo,2021,54000,4190000,Petrol,Unregistered,Original,Imported,Automatic,Used,"Airline Avenue, Islamabad","it's 2021 model fresh import, perfect engine s...","ABS, Air Bags, AM/FM Radio, CD Player, Cassett...",['https://images.olx.com.pk/thumbnails/4039460...,https://www.olx.com.pk/item/fresh-import-passo...
1,1080125520,Suzuki ravi,Suzuki,Ravi,2018,95000,1300000,Petrol,Karachi,Original,Local,Manual,Used,"Kahuta, Rawalpindi",Suzuki ravi 2018 col,AM/FM Radio,['https://images.olx.com.pk/thumbnails/4102504...,https://www.olx.com.pk/item/suzuki-ravi-iid-10...
2,1080748789,Suzuki bolan 2015 contact 03112271054,Suzuki,Bolan,2015,50000,800000,Petrol,Karachi,Original,Local,Manual,Used,"Lyari Expressway, Karachi",Suzuki bolan model 2015 reg 2022 ghadi me koi ...,Rear speakers,['https://images.olx.com.pk/thumbnails/4139520...,https://www.olx.com.pk/item/suzuki-bolan-2015-...
3,1076081635,Diahatsu Move 2013,Daihatsu,Move,2013,94000,2155000,Petrol,Lahore,Original,Imported,Automatic,Used,"New Amir Town, Lahore",Move Push start \nHome Used car. \nModel 2013....,"ABS, Air Bags, Air Conditioning, Alloy Rims, A...",['https://images.olx.com.pk/thumbnails/3865337...,https://www.olx.com.pk/item/diahatsu-move-2013...
4,1080812928,Suzuki Swift DLX 2011 miner tuchap,Suzuki,Swift,2011,126544,1440000,Petrol,Karachi,Original,Local,Manual,Used,"Shadman 2, Karachi",Suzuki Swift DLX\nAbS Break 100%\nengine 100%\...,"ABS, Air Conditioning, Alloy Rims, AM/FM Radio...",['https://images.olx.com.pk/thumbnails/4143509...,https://www.olx.com.pk/item/suzuki-swift-dlx-2...

In [27]:
#to drop/remove/delete the the columns

to_drop = ["Images URL's",
            'Car Profile',
            'Seller Location',
            'Registration city',
            'Description'
            ]

df.drop(to_drop, inplace=True, axis=1)

In [28]:
#to see the all data 

df.head()

,Ad ID,Car Name,Make,Model,Year,KM's driven,Price,Fuel,Car documents,Assembly,Transmission,Condition,Car Features
0,1079071571,fresh import Passo 2021model,Toyota,Passo,2021,54000,4190000,Petrol,Original,Imported,Automatic,Used,"ABS, Air Bags, AM/FM Radio, CD Player, Cassett..."
1,1080125520,Suzuki ravi,Suzuki,Ravi,2018,95000,1300000,Petrol,Original,Local,Manual,Used,AM/FM Radio
2,1080748789,Suzuki bolan 2015 contact 03112271054,Suzuki,Bolan,2015,50000,800000,Petrol,Original,Local,Manual,Used,Rear speakers
3,1076081635,Diahatsu Move 2013,Daihatsu,Move,2013,94000,2155000,Petrol,Original,Imported,Automatic,Used,"ABS, Air Bags, Air Conditioning, Alloy Rims, A..."
4,1080812928,Suzuki Swift DLX 2011 miner tuchap,Suzuki,Swift,2011,126544,1440000,Petrol,Original,Local,Manual,Used,"ABS, Air Conditioning, Alloy Rims, AM/FM Radio..."

In [29]:
#to make the unique data

df['Make'].is_unique
True

True

In [30]:
#changing the index of the data

df = df.set_index('Make')
df.head()

,Ad ID,Car Name,Model,Year,KM's driven,Price,Fuel,Car documents,Assembly,Transmission,Condition,Car Features
Make,,,,,,,,,,,,
Toyota,1079071571,fresh import Passo 2021model,Passo,2021,54000,4190000,Petrol,Original,Imported,Automatic,Used,"ABS, Air Bags, AM/FM Radio, CD Player, Cassett..."
Suzuki,1080125520,Suzuki ravi,Ravi,2018,95000,1300000,Petrol,Original,Local,Manual,Used,AM/FM Radio
Suzuki,1080748789,Suzuki bolan 2015 contact 03112271054,Bolan,2015,50000,800000,Petrol,Original,Local,Manual,Used,Rear speakers
Daihatsu,1076081635,Diahatsu Move 2013,Move,2013,94000,2155000,Petrol,Original,Imported,Automatic,Used,"ABS, Air Bags, Air Conditioning, Alloy Rims, A..."
Suzuki,1080812928,Suzuki Swift DLX 2011 miner tuchap,Swift,2011,126544,1440000,Petrol,Original,Local,Manual,Used,"ABS, Air Conditioning, Alloy Rims, AM/FM Radio..."

In [34]:
#changed the name of the column

new_column_names = {
        "Make": "Company_name",
        "Ad ID": "CAr_ID",
    }
   
data = df.rename(columns=new_column_names)

In [35]:
#to see the data

data.columns

Index(['CAr_ID', 'Car Name', 'Model', 'Year', 'KM's driven', 'Price', 'Fuel',
       'Car documents', 'Assembly', 'Transmission', 'Condition',
       'Car Features'],
      dtype='object')

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9179 entries, Toyota to Daihatsu
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CAr_ID         9179 non-null   int64
 1   Car Name       9179 non-null   object
 2   Model          9179 non-null   object
 3   Year           9179 non-null   int64
 4   KM's driven    9179 non-null   int64
 5   Price          9179 non-null   int64
 6   Fuel           9179 non-null   object
 7   Car documents  9179 non-null   object
 8   Assembly       9179 non-null   object
 9   Transmission   9179 non-null   object
 10  Condition      9179 non-null   object
 11  Car Features   9179 non-null   object
dtypes: int64(4), object(8)
memory usage: 932.2+ KB

In [37]:
#duplicate data

data.loc[data.duplicated(keep=False)]

,CAr_ID,Car Name,Model,Year,KM's driven,Price,Fuel,Car documents,Assembly,Transmission,Condition,Car Features
Make,,,,,,,,,,,,
Suzuki,1079496823,WagonR AGS total genuine,Wagon R,2020,54000,2830000,Petrol,Original,Local,Automatic,Used,"ABS, Air Bags, Alloy Rims, AM/FM Radio, CD Pla..."
Suzuki,1080826824,Wagon R 2014 VXL,Wagon R,2014,125000,1600000,Petrol,Original,Local,Manual,Used,"Air Bags, Air Conditioning, AM/FM Radio, Front..."
Suzuki,1080755995,eminent blue mehran vxr 2009 model for sale,Mehran VXR,2009,96000,620000,Petrol,Original,Local,Manual,Used,Air Conditioning
Suzuki,1080780702,swift,Swift,2017,90000,2100000,Petrol,Original,Local,Manual,Used,"ABS, Air Bags, AM/FM Radio, DVD Player, Front ..."
Suzuki,1080786841,foll saond sistam,Baleno,2005,75000,560000,Petrol,Duplicate,Local,Manual,Used,ABS
...,...,...,...,...,...,...,...,...,...,...,...,...
Suzuki,1080315225,2018 in good condition,Mehran VXR,2018,96000,1395000,Petrol,Original,Local,Manual,Used,"Air Conditioning, AM/FM Radio"
Toyota,1080195710,toyota Yaris Gli,Yaris,2020,40000,3575000,Petrol,Original,Local,Manual,Used,"ABS, Air Bags, Air Conditioning, AM/FM Radio, ..."
Suzuki,1080824857,Govt. Officer Wagon R VXL,Wagon R,2019,47500,2295000,Petrol,Original,Local,Manual,Used,"Air Conditioning, Alloy Rims, AM/FM Radio, Fro..."
Suzuki,1080360303,suzuki cultus Model 2010,Cultus VXR,2010,1234,985000,Petrol,Original,Local,Manual,Used,"Alloy Rims, CD Player, DVD Player, Front Speak..."
Suzuki,1080778272,Suzuki Swift Dlx 2018,Swift,2018,151000,2425000,Petrol,Original,Local,Manual,Used,"ABS, Air Conditioning, Navigation System, Powe..."

In [38]:
#to count the rows and columns

print(df.shape)  #result is (rows,coloums)

(9179, 12)

In [39]:
#top 5 rows

df.head(5)

,Ad ID,Car Name,Model,Year,KM's driven,Price,Fuel,Car documents,Assembly,Transmission,Condition,Car Features
Make,,,,,,,,,,,,
Toyota,1079071571,fresh import Passo 2021model,Passo,2021,54000,4190000,Petrol,Original,Imported,Automatic,Used,"ABS, Air Bags, AM/FM Radio, CD Player, Cassett..."
Suzuki,1080125520,Suzuki ravi,Ravi,2018,95000,1300000,Petrol,Original,Local,Manual,Used,AM/FM Radio
Suzuki,1080748789,Suzuki bolan 2015 contact 03112271054,Bolan,2015,50000,800000,Petrol,Original,Local,Manual,Used,Rear speakers
Daihatsu,1076081635,Diahatsu Move 2013,Move,2013,94000,2155000,Petrol,Original,Imported,Automatic,Used,"ABS, Air Bags, Air Conditioning, Alloy Rims, A..."
Suzuki,1080812928,Suzuki Swift DLX 2011 miner tuchap,Swift,2011,126544,1440000,Petrol,Original,Local,Manual,Used,"ABS, Air Conditioning, Alloy Rims, AM/FM Radio..."

In [43]:
#for counting data from the dataset

df['Year'].value_counts()

Year
2018    601
2017    563
2007    551
2015    537
2016    535
2006    524
2021    499
2005    484
2014    466
2012    422
2013    415
2011    396
2008    385
2019    384
2004    365
2010    355
2020    338
2022    327
2009    278
2003    259
2001    166
2002    159
2000    112
2023     55
1993      1
1989      1
2024      1
Name: count, dtype: int64

In [46]:
#displayinf last five rows of dataset
data.tail()

,CAr_ID,Car Name,Model,Year,KM's driven,Price,Fuel,Car documents,Assembly,Transmission,Condition,Car Features
Make,,,,,,,,,,,,
Suzuki,1080606577,Suzuki Wagon R Japanese 660cc sale/exchange,Wagon R,2014,115000,2725000,Petrol,Original,Imported,Automatic,Used,"ABS, Air Bags, Air Conditioning, Alloy Rims, A..."
Suzuki,1080268395,wegon R VXL 2017,Wagon R,2017,100000,1850000,Petrol,Original,Local,Manual,Used,"Air Conditioning, CD Player, Power Steering, P..."
KIA,1080570925,Good condition,Spectra,2001,123456,1100000,Petrol,Original,Imported,Automatic,Used,"Air Conditioning, AM/FM Radio, DVD Player, Pow..."
Suzuki,1075792717,Suzuki Alto vxr,Alto,2009,89000,970000,Petrol,Original,Imported,Manual,Used,"Air Conditioning, AM/FM Radio, Front Speakers,..."
Daihatsu,1080569552,Move Custom,Move,2016,95000,2050000,Petrol,Original,Imported,Automatic,Used,"ABS, Air Bags, Air Conditioning, Alloy Rims, A..."

In [48]:
data.duplicated()

Make
Toyota      False
Suzuki      False
Suzuki      False
Daihatsu    False
Suzuki      False
            ...
Suzuki      False
Suzuki      False
KIA         False
Suzuki      False
Daihatsu    False
Length: 9179, dtype: bool